### ISSUE TITLE
Got an TypeError.

### ISSUE THREAD

**Issue by nkh0472** [jaflo/screenStitch#1]
When opening first .bmp file, an error was showed as bellow:
```
Made by jaflo on github
Choose images to compare
Traceback (most recent call last):
  File "X:\sandboxtmp\screenStitch.py", line 76, in <module>
    fullimage = Image.new("RGB", (rightmost-leftmost-11, 9999), "black")
  File "H:\Miniconda3\envs\py2\lib\site-packages\PIL\Image.py", line 1763, in new
    return Image()._new(core.fill(mode, size, color))
TypeError: integer argument expected, got float
```
My environment is :
```
# packages in environment at H:\Miniconda3\envs\py2:
#
# Name                    Version                   Build  Channel
certifi                   2016.2.28                py27_0    defaults
pil                       1.1.7                    py27_0    defaults
pip                       9.0.1                    py27_1    defaults
python                    2.7.13                        1    defaults
setuptools                36.4.0                   py27_1    defaults
vc                        9                    h7299396_1    defaults
vs2008_runtime            9.00.30729.1         hfaea7d5_1    defaults
wheel                     0.35.1                     py_0    defaults
wincertstore              0.2              py27hf04cefb_0    defaults
```

**Comment by nkh0472** [comment]
More information of the file: 
```
CompleteName                     : X:\sandboxtmp\Image01.bmp
Format/String                    : Bitmap
FileSize/String                  : 4.00 MiB

Format/String                    : RGB
Width/String                     : 1 844 pix
Height/String                    : 758 pix
ColorSpace                       : RGB
BitDepth/String                  : 24 bit
```

**Comment by jaflo** [comment]
Looks like there 1e9 (`leftmost`) is a float. On line 76, could you change

    fullimage = Image.new("RGB", (rightmost-leftmost-11, 9999), "black")

to 

    fullimage = Image.new("RGB", int(rightmost-leftmost-11, 9999), "black")

and see if that works? If it does I can fix it in the repo (or you can make a PR if you want to).

**Comment by nkh0472** [comment]
New error:
```
Made by jaflo on github
Choose images to compare
Traceback (most recent call last):
  File "X:\screenStitch.py", line 76, in <module>
    fullimage = Image.new("RGB", int(rightmost-leftmost-11, 9999), "black")
TypeError: int() can't convert non-string with explicit base
```
PS: Does it possible to make this file fit to python 3 ?

**Comment by jaflo** [comment]
I have updated the file to support Python 3 and it should run now (runs for me on Python 3.8.5). Note that it seems fickle with how the screenshots are fed in and how they are cropped. I don't remember much of the logic since I wrote this a while ago, but the algorithm could be improved.

**Comment by nkh0472** [comment]
Thanks a lot.
